version: "3"
services:
  genesis:
    container_name: "genesis_videoapi"
    build: .
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Jakarta
      - DEBIAN_FRONTEND=noninteractive
      - FLASK_APP=/home/genesis/src/run.py
      - FLASK_DEBUG=1
      - ENV=devel